import Head from "next/head";
import Footer from "../components/Footer";
import Button from "../components/Button";
import Textarea from "../components/Textarea";

export default function Home() {
  return (
    <div className="h-screen flex-col justify-between bg-black p-5">
      <Head>
        <title>JSON Style</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="text-2xl text-center">JSON STYLE</p>
        <div className="space-y-5">
          <Textarea
            className="w-1/2"
            rows={10}
            label="JSON String"
            onChange={(e) => console.log(e.target.value)}
          />
          <Button className="ml-1" label="Click Me" />
        </div>
      </main>
      <Footer />
    </div>
  );
}
